# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************
name: Toolchains QNX Tests
on:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  toolchains-qnx-tests-build-all:
    runs-on: ubuntu-latest
    environment: workflow-approval
    defaults:
      run:
        working-directory: ./tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.14.0
      - name: Setup QNX License
        env:
          SCORE_QNX_LICENSE: ${{ secrets.SCORE_QNX_LICENSE }}
        run: |
          mkdir -p /opt/score_qnx/license
          echo "${SCORE_QNX_LICENSE}" | base64 --decode > /opt/score_qnx/license/licenses
      - name: Install qemu
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-system
      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
      # ---------- x86_64 ----------
      - name: Build (x86_64)
        env:
          SCORE_QNX_USER: ${{ secrets.SCORE_QNX_USER }}
          SCORE_QNX_PASSWORD: ${{ secrets.SCORE_QNX_PASSWORD }}
        run: |
          bazel build //... --config=x86_64-qnx \
            --credential_helper=*.qnx.com=${{ github.workspace }}/tools/qnx_credential_helper.py
      - name: Smoke boot (x86_64)
        run: |
          bazel run --config=x86_64-qnx //:run_qemu
      # ---------- aarch64 ----------
      - name: Build (aarch64)
        env:
          SCORE_QNX_USER: ${{ secrets.SCORE_QNX_USER }}
          SCORE_QNX_PASSWORD: ${{ secrets.SCORE_QNX_PASSWORD }}
        run: |
          bazel build //... --config=aarch64-qnx \
            --credential_helper=*.qnx.com=${{ github.workspace }}/tools/qnx_credential_helper.py
      - name: Smoke boot (aarch64)
        run: |
          bazel run --config=aarch64-qnx //:run_qemu
      - name: Cleanup QNX License
        if: always()
        run: |
          rm -rf /opt/score_qnx
          rm -rf "${HOME}/.cache/bazel"
